---
- name: gather facts play
  hosts: all
  gather_facts: yes
  tasks:
  - name: print
    debug: 
      msg: turnoff gather facts
  - name: cpus
    debug:
      msg: "cpus :{{ansible_processor_cores}}"
  - name: total memory
    debug:
      msg: "total available memory: {{ansible_memory_mb.real.total}}"    
...