---
- name: loop over simple list of values play
  hosts: all
  tasks:
  - name: install s/w packages
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    become: yes
    loop:
      - openjdk-11-jdk
      - vim
      - tree
      - git
      - maven
      - net-tools
...