---
- name: failedwhen play
  hosts: all
  tasks:
  - name: check diskspace
    shell: "df /dev/sda1 | tail -1 | awk '{print $4}'"
    register: diskspace
    failed_when: "diskspace.stdout | float < 41943040"
  # - name: debug diskspace                                        
  #   debug:
  #     msg: "{{diskspace}}"  
  - name: install jdk
    apt:
      name: openjdk-11-jdk
      state: present
      update_cache: yes
    become: yes

...