---
- name: by default handlers will not be executed play
  hosts: all
  tasks:
  - name: debug
    debug:
      msg: debug task
    notify:
      - handler1  
  handlers:
  - name: handler1
    debug:
      msg: handler      
...